[package]
name = "file-conversion-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.4"
image = "0.24.6"
native-dialog = "0.6.3"
